In [117]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

from itertools import chain
from itertools import combinations

In [118]:
data = pd.read_csv('movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
1528,tt0446046,30000000,34742066,Take the Lead,Antonio Banderas|Rob Brown|Yaya DaCosta|Alfre ...,Liz Friedlander,Never Follow,A former professional dancer volunteers to tea...,108,Music,New Line Cinema|Tiara Blu Films,3/17/2006,6.4,2006
419,tt1038919,40000000,136000000,The Bounty Hunter,Gerard Butler|Jennifer Aniston|Gio Perez|Siobh...,Andy Tennant,"It's a Job. It Isn't Personal. Well, Maybe a L...",Milo Boyd is a bounty hunter whose latest gig ...,110,Action,Columbia Pictures|Original Film|Relativity Med...,3/16/2010,5.5,2010
1237,tt2387559,26000000,51164106,Delivery Man,Vince Vaughn|Cobie Smulders|Chris Pratt|Britt ...,Ken Scott,You're never quite ready for what life delivers.,An affable underachiever finds out he's father...,105,Comedy,DreamWorks SKG|Touchstone Pictures,10/10/2013,6.1,2013
124,tt2245084,165000000,652105443,Big Hero 6,Scott Adsit|Ryan Potter|Daniel Henney|T.J. Mil...,Don Hall|Chris Williams,From the creators of Wreck-it Ralph and Frozen,The special bond that develops between plus-si...,102,Adventure|Family|Animation|Action|Comedy,Walt Disney Pictures|Walt Disney Animation Stu...,10/24/2014,7.8,2014
323,tt1057500,60000000,122233971,Invictus,Morgan Freeman|Matt Damon|Tony Kgoroge|Patrick...,Clint Eastwood,His people needed a leader. He gave them a cha...,Newly elected President Nelson Mandela knows h...,134,Drama|History,Spyglass Entertainment|Malpaso Productions|Rev...,12/10/2009,6.9,2009

In [119]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

# Предобработка

In [120]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

# profit= revenue-budget формула для получения Прибыли от фильма: Прибыль = Сборы - Бюджет
data['profit']=data.revenue - data.budget



# извлечение месяца из даты
movie_month=data.copy()
data['Date'] = pd.to_datetime(data['release_date'])
movie_month.release_date = data['Date'].dt.month

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [121]:
# в словарь вставляем номер вопроса и ваш ответ на него
# Пример: 
answers['1'] = '2. Spider-Man 3 (tt0413300)'
# запишите свой вариант ответа
answers['1'] = 'Pirates of the Caribbean: On Stranger Tides (tt1298650)' # +
# если ответили верно, можете добавить комментарий со значком "+"

In [122]:
# тут пишем ваш код для решения данного вопроса:
data.groupby('budget').max()

,imdb_id,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,Date
budget,,,,,,,,,,,,,,,
5000000,tt4178092,368744044,Wonderland,Val Kilmer|Dylan McDermott|Kate Bosworth|Josh ...,Walt Becker,You're one of us now.,"Yearning for an evening without their kids, so...",119,Thriller|Mystery,Universal Studios|Universal Pictures|Voltage P...,9/8/2013,7.8,2015,363744044,2015-10-22
5500000,tt2397535,3000000,Predestination,Ethan Hawke|Sarah Snook|Noah Taylor|Christophe...,Michael Spierig|Peter Spierig,To save the future he must reshape the past.,Predestination chronicles the life of a Tempor...,97,Science Fiction|Thriller,Screen Australia|Screen Queensland|Blacklab En...,8/28/2014,7.2,2014,-2500000,2014-08-28
6000000,tt3787590,119114517,We Are Your Friends,Zac Efron|Emily Ratajkowski|Wes Bentley|Nick R...,Steven Brill|Elizabeth Banks|Steve Carr|Rusty ...,There's more than one way to take a life.,"Young Scottish doctor, Nicholas Garrigan decid...",122,Drama|Thriller,Working Title Films,9/7/2012,8.0,2015,113114517,2015-11-13
6400000,tt1655420,35057696,Young Adam,Michelle Williams|Eddie Redmayne|Kenneth Brana...,Simon Curtis,Sometimes You Just Need to Get Away,Sir Laurence Olivier is making a movie in Lond...,99,Drama|Thriller|Crime|Romance,Recorded Picture Company (RPC),9/26/2003,6.7,2011,28657696,2011-10-17
6500000,tt3322940,255273813,The Pyramid,Sandra Bullock|Don Cheadle|Matt Dillon|Michael...,Zal Batmanglij,You think you know who you are. You have no idea.,The chief spokesperson and lobbyist Nick Naylo...,116,Horror,Scott Free Productions,9/5/2005,7.1,2014,248773813,2014-12-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258000000,tt0413300,890871626,Spider-Man 3,Tobey Maguire|Kirsten Dunst|James Franco|Thoma...,Sam Raimi,The battle within.,The seemingly invincible Spider-Man goes up ag...,139,Fantasy|Action|Adventure,Columbia Pictures|Laura Ziskin Productions|Mar...,5/1/2007,5.8,2007,632871626,2007-05-01
260000000,tt0401729,591794936,Tangled,Zachary Levi|Mandy Moore|Donna Murphy|Ron Perl...,Nathan Greno|Byron Howard,They're taking adventure to new lengths.,When the kingdom's most wanted-and most charmi...,132,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,3/7/2012,7.3,2012,331794936,2012-03-07
280000000,tt2395427,1405035767,Avengers: Age of Ultron,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,Joss Whedon,A New Age Has Come.,When Tony Stark tries to jumpstart a dormant p...,141,Action|Adventure|Science Fiction,Marvel Studios|Prime Focus|Revolution Sun Studios,4/22/2015,7.4,2015,1125035767,2015-04-22
300000000,tt0449088,961000000,Pirates of the Caribbean: At World's End,Johnny Depp|Orlando Bloom|Keira Knightley|Geof...,Gore Verbinski,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...",169,Adventure|Fantasy|Action,Walt Disney Pictures|Jerry Bruckheimer Films|S...,5/19/2007,6.8,2007,661000000,2007-05-19
380000000,tt1298650,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011,641683000,2011-05-11

ВАРИАНТ 2

In [123]:
# можно добавлять разные варианты решения

data.budget.sort_values(ascending=False)

723     380000000
1669    300000000
14      280000000
380     260000000
1014    260000000
          ...
805       5000000
1817      5000000
277       5000000
1173      5000000
885       5000000
Name: budget, Length: 1889, dtype: int64

# 2. Какой из фильмов самый длительный (в минутах)?

In [124]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = 'Gods and Generals (tt0279111)'

In [125]:
data.groupby('runtime').max()

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,genres,production_companies,release_date,vote_average,release_year,profit,Date
runtime,,,,,,,,,,,,,,,
63,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011,-15540000,2011-04-13
72,tt0283426,20000000,135680000,The Jungle Book 2,John Goodman|Haley Joel Osment|Mae Whitman|Phi...,Steve Trenbirth,The Classic Continues,The classic tale of 'Peter Pan' continues in D...,Family|Animation|Adventure,Walt Disney Pictures|Walt Disney Television An...,2/7/2003,6.2,2003,115680000,2003-02-07
76,tt0361089,110000000,103951461,Valiant,Randy Quaid|Steve Buscemi|Judi Dench|Cuba Good...,Will Finn|John Sanford,"Some pigeons eat crumbs, others make history.",The animated comedy tells the story of a lowly...,Western|Animation|Family|Comedy|Music,Walt Disney Pictures|Walt Disney Feature Anima...,4/2/2004,5.8,2005,-6048539,2005-03-25
77,tt0121164,40000000,117195061,Corpse Bride,Johnny Depp|Helena Bonham Carter|Emily Watson|...,Tim Burton|Mike Johnson,There's been a grave misunderstanding.,"Set in a 19th-century european village, this s...",Romance|Fantasy|Animation|Music,Tim Burton Animation Company|Will Vinton Studi...,9/9/2005,7.0,2005,77195061,2005-09-09
78,tt0243585,120000000,169956806,The Emperor's New Groove,Michael J. Fox|Geena Davis|Hugh Laurie|Jonatha...,Rob Minkoff,It's All About.....ME!,"Stuart, an adorable white mouse, still lives h...",Family|Adventure|Animation|Comedy,Walt Disney Pictures|Walt Disney Feature Anima...,7/19/2002,6.9,2002,69327687,2002-07-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,tt0213149,140000000,449220945,Pearl Harbor,Ben Affleck|Josh Hartnett|Kate Beckinsale|Cuba...,Michael Bay,"December 7, 1941 - A day that shall live in in...",The lifelong friendship between Rafe McCawley ...,History|Romance|War,Jerry Bruckheimer Films|Touchstone Pictures,5/21/2001,6.6,2001,309220945,2001-05-21
187,tt0360717,207000000,550000000,King Kong,Naomi Watts|Jack Black|Adrien Brody|Thomas Kre...,Peter Jackson,The eighth wonder of the world.,"In 1933 New York, an overly ambitious movie pr...",Adventure|Drama|Action,WingNut Films|Universal Pictures|Big Primate P...,12/14/2005,6.4,2005,343000000,2005-12-14
191,tt0462322,67000000,25037897,Grindhouse,Kurt Russell|ZoÃ« Bell|Rosario Dawson|Vanessa ...,Robert Rodriguez|Eli Roth|Quentin Tarantino|Ed...,A double feature that'll tear you in two!,Two full length feature horror movies written ...,Thriller|Action|Horror,Big Talk Productions|Yer Dead Productions|Wein...,4/6/2007,6.5,2007,-41962103,2007-04-06
201,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003,1024888979,2003-12-01
214,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003,-43076064,2003-02-21

# 3. Какой из фильмов самый короткий (в минутах)?

In [126]:
answers['3'] = 'Winnie the Pooh (tt1449283)'

data.groupby('runtime').min()

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,genres,production_companies,release_date,vote_average,release_year,profit,Date
runtime,,,,,,,,,,,,,,,
63,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011,-15540000,2011-04-13
72,tt0280030,20000000,109862682,Return to Never Land,Harriet Owen|Blayne Weaver|Jeff Bennett|Kath S...,Robin Budd|Donovan Cook,Feel the jungle beat,"Mowgli, missing the jungle and his old friends...",Adventure|Fantasy|Animation|Family,Walt Disney Pictures|Walt Disney Television An...,2/14/2002,5.6,2002,89862682,2002-02-14
76,tt0299172,35000000,19478106,Home on the Range,Ewan McGregor|Ricky Gervais|Tim Curry|Jim Broa...,Gary Chapman,Bust a Moo.,The Little Piece of Heaven family farm is abou...,Animation|Family|Adventure,Vanguard Films|Scanbox,3/25/2005,5.3,2004,-15521894,2004-04-02
77,tt0121164,40000000,117195061,Corpse Bride,Johnny Depp|Helena Bonham Carter|Emily Watson|...,Tim Burton|Mike Johnson,There's been a grave misunderstanding.,"Set in a 19th-century european village, this s...",Romance|Fantasy|Animation|Music,Tim Burton Animation Company|Will Vinton Studi...,9/9/2005,7.0,2005,77195061,2005-09-09
78,tt0120917,100000000,169327687,Stuart Little 2,David Spade|John Goodman|Eartha Kitt|Patrick W...,Mark Dindal,A Little Goes A Long Way,Kuzco is a self-centered emperor who summons P...,Adventure|Animation|Comedy|Family|Fantasy,Columbia Pictures|Sony Pictures Entertainment,12/9/2000,5.4,2000,49956806,2000-12-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,tt0213149,140000000,449220945,Pearl Harbor,Ben Affleck|Josh Hartnett|Kate Beckinsale|Cuba...,Michael Bay,"December 7, 1941 - A day that shall live in in...",The lifelong friendship between Rafe McCawley ...,History|Romance|War,Jerry Bruckheimer Films|Touchstone Pictures,5/21/2001,6.6,2001,309220945,2001-05-21
187,tt0360717,207000000,550000000,King Kong,Naomi Watts|Jack Black|Adrien Brody|Thomas Kre...,Peter Jackson,The eighth wonder of the world.,"In 1933 New York, an overly ambitious movie pr...",Adventure|Drama|Action,WingNut Films|Universal Pictures|Big Primate P...,12/14/2005,6.4,2005,343000000,2005-12-14
191,tt0462322,67000000,25037897,Grindhouse,Kurt Russell|ZoÃ« Bell|Rosario Dawson|Vanessa ...,Robert Rodriguez|Eli Roth|Quentin Tarantino|Ed...,A double feature that'll tear you in two!,Two full length feature horror movies written ...,Thriller|Action|Horror,Big Talk Productions|Yer Dead Productions|Wein...,4/6/2007,6.5,2007,-41962103,2007-04-06
201,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003,1024888979,2003-12-01
214,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003,-43076064,2003-02-21

# 4. Какова средняя длительность фильмов?

In [127]:
answers['4'] = 109.6585494970884

data.runtime.mean()

109.6585494970884

# 5. Каково медианное значение длительности фильмов?

In [128]:
answers['5'] = 107.0

data.runtime.median()

107.0

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [129]:
# лучше код получения столбца profit вынести в Предобработку что в начале
answers['6'] = 'Avatar (tt0499549)'
data.groupby('profit').max()

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,Date
profit,,,,,,,,,,,,,,,
-165710090,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,2013-07-03
-119180039,tt0318974,145000000,25819961,The Alamo,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,John Lee Hancock,You will never forget,Based on the 1836 standoff between a group of ...,137,Western|History|War,Imagine Entertainment|Touchstone Pictures,4/7/2004,5.9,2004,2004-04-07
-111007242,tt1305591,150000000,38992758,Mars Needs Moms,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,Simon Wells,Mom needs a little space.,"When Martians suddenly abduct his mom, mischie...",88,Adventure|Animation|Family,Walt Disney Animation Studios,3/9/2011,5.5,2011,2011-03-09
-92896027,tt0180052,100000000,7103973,The Adventures of Pluto Nash,Eddie Murphy|Randy Quaid|Rosario Dawson|Joe Pa...,Ron Underwood,Action's future has arrived...,"The year is 2087, the setting is the moon. Edd...",95,Action|Comedy|Science Fiction,Village Roadshow Pictures|Castle Rock Entertai...,8/15/2002,4.6,2002,2002-08-15
-84540684,tt0424095,149000000,64459316,Flushed Away,Hugh Jackman|Kate Winslet|Ian McKellen|Jean Re...,David Bowers|Sam Fell,Someone's Going Down,"London high-society mouse, Roddy is flushed do...",85,Adventure|Animation|Comedy|Family,Aardman Animations|DreamWorks Animation,10/22/2006,6.0,2006,2006-10-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299557910,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,2012-04-25
1316249360,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015,2015-04-01
1363528810,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015,2015-06-09
1868178225,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015,2015-12-15
2544505847,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2009-12-10

# 7. Какой фильм самый убыточный?

In [130]:
answers['7'] = 'The Lone Ranger (tt1210819)'
data.groupby('profit').max()

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,Date
profit,,,,,,,,,,,,,,,
-165710090,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,2013-07-03
-119180039,tt0318974,145000000,25819961,The Alamo,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,John Lee Hancock,You will never forget,Based on the 1836 standoff between a group of ...,137,Western|History|War,Imagine Entertainment|Touchstone Pictures,4/7/2004,5.9,2004,2004-04-07
-111007242,tt1305591,150000000,38992758,Mars Needs Moms,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,Simon Wells,Mom needs a little space.,"When Martians suddenly abduct his mom, mischie...",88,Adventure|Animation|Family,Walt Disney Animation Studios,3/9/2011,5.5,2011,2011-03-09
-92896027,tt0180052,100000000,7103973,The Adventures of Pluto Nash,Eddie Murphy|Randy Quaid|Rosario Dawson|Joe Pa...,Ron Underwood,Action's future has arrived...,"The year is 2087, the setting is the moon. Edd...",95,Action|Comedy|Science Fiction,Village Roadshow Pictures|Castle Rock Entertai...,8/15/2002,4.6,2002,2002-08-15
-84540684,tt0424095,149000000,64459316,Flushed Away,Hugh Jackman|Kate Winslet|Ian McKellen|Jean Re...,David Bowers|Sam Fell,Someone's Going Down,"London high-society mouse, Roddy is flushed do...",85,Adventure|Animation|Comedy|Family,Aardman Animations|DreamWorks Animation,10/22/2006,6.0,2006,2006-10-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299557910,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,2012-04-25
1316249360,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015,2015-04-01
1363528810,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015,2015-06-09
1868178225,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015,2015-12-15
2544505847,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2009-12-10

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [131]:
answers['8'] = 1478
data.groupby(data.revenue > data.budget).count()

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,Date
False,411,411,411,411,411,411,411,411,411,411,411,411,411,411,411,411
True,1478,1478,1478,1478,1478,1478,1478,1478,1478,1478,1478,1478,1478,1478,1478,1478

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [132]:
answers['9'] = 'The Dark Knight (tt0468569)' # +

year_search=data.groupby('revenue')[['original_title','release_year','imdb_id']].max().sort_values('revenue', ascending=False)
year_search[year_search.release_year==2008]

,original_title,release_year,imdb_id
revenue,,,
1001921825,The Dark Knight,2008,tt0468569
786636033,Indiana Jones and the Kingdom of the Crystal S...,2008,tt0367882
631744560,Kung Fu Panda,2008,tt0441773
624029371,Hancock,2008,tt0448157
609841637,Mamma Mia!,2008,tt0795421
...,...,...,...
6673422,What Just Happened,2008,tt0486674
5926410,Transsiberian,2008,tt0800241
5530764,The Brothers Bloom,2008,tt0844286
3533227,The Midnight Meat Train,2008,tt0805570
2033165,Mutant Chronicles,2008,tt0490181

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [133]:
answers['10'] = 'The Lone Ranger (tt1210819)'

year_search=data.groupby('profit')[['original_title','release_year','imdb_id']].max().sort_values('profit', ascending=False)
year_search[(year_search.release_year> 2011) & (year_search.release_year< 2015)]

                              original_title  release_year    imdb_id
profit
 1299557910                     The Avengers          2012  tt0848228
 1124219009                           Frozen          2013  tt2294629
 1015439994                       Iron Man 3          2013  tt1300854
 908561013                           Skyfall          2012  tt1074638
 894761885                   Despicable Me 2          2013  tt1690953
...                                      ...           ...        ...
-45510171                 Bullet to the Head          2013  tt1308729
-51337973    Legends of Oz: Dorothy's Return          2013  tt0884726
-51893525                        Upside Down          2012  tt1374992
-68351500                           R.I.P.D.          2013  tt0790736
-165710090                   The Lone Ranger          2013  tt1210819

[367 rows x 3 columns]

# 11. Какого жанра фильмов больше всего?

In [134]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале

answers['11'] = 'Drama'

genres_counter=Counter()
Counter(data.genres.str.split('|').sum()).most_common(1)

[('Drama', 782)]

ВАРИАНТ 2

In [135]:
def splitter(string):
    result = string.str.split('|')
    return result

data['genresList'] = splitter(data['genres'])
genresList = data['genresList'].sum()
Counter(genresList)

Counter({'Action': 582,
         'Adventure': 415,
         'Science Fiction': 248,
         'Thriller': 596,
         'Fantasy': 222,
         'Crime': 315,
         'Western': 19,
         'Drama': 782,
         'Family': 260,
         'Animation': 139,
         'Comedy': 683,
         'Mystery': 168,
         'Romance': 308,
         'War': 58,
         'History': 62,
         'Music': 64,
         'Horror': 176,
         'Documentary': 8,
         'Foreign': 2})

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [136]:
answers['12'] = 'Action'

genre_movies = data.copy()
genre_movies.genres = data.genres.str.split('|')
genre_movies = genre_movies.explode('genres').groupby('genres')['profit'].max().sort_values(ascending=False)
genre_movies

genres
Action             2544505847
Science Fiction    2544505847
Adventure          2544505847
Fantasy            2544505847
Thriller           1363528810
Crime              1316249360
Family             1202817822
Animation          1124219009
Comedy             1082730962
Drama               831041287
Mystery             788212738
Romance             709000000
War                 490523427
Horror              435349010
History             399211549
Western             397950503
Music               380809770
Documentary         113114517
Foreign              -5000000
Name: profit, dtype: int64

# 13. У какого режиссера самые большие суммарные кассовые сборы?

In [137]:
answers['13'] = 'Peter Jackson'

data.groupby('director')['revenue'].sum().sort_values(ascending=False)

director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 957, dtype: int64

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [138]:
answers['14'] = 'Robert Rodriguez'

action_movies=data.copy()
action_movies = data[data.genres.str.contains('Action', na=False)].director.str.split('|').explode('director')
action_movies.value_counts()

Robert Rodriguez      9
Paul W.S. Anderson    7
Michael Bay           7
Ridley Scott          6
Antoine Fuqua         6
                     ..
Peter Farrelly        1
Steve Carr            1
Jimmy Hayward         1
Taylor Hackford       1
Noam Murro            1
Name: director, Length: 364, dtype: int64

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [139]:
answers['15'] = 'Chris Hemsworth'

actor_movie=data[data.release_year == 2012].copy()
actor_movie.cast = actor_movie.cast.str.split('|')
actor_movie = actor_movie.explode('cast').groupby('cast')['revenue'].sum().sort_values(ascending=False)
actor_movie

cast
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Chris Evans          1519557910
Robert Downey Jr.    1519557910
                        ...
Jason Bateman           3428048
Danny Huston            2106557
Sami Gayle              2106557
Josh Lucas              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [140]:
answers['16'] = 'Matt Damon'

actor_high_budget=data[data.budget > data.budget.mean()].copy()
actor_high_budget.cast = actor_high_budget.cast.str.split('|')
actor_high_budget = actor_high_budget.explode('cast').groupby('cast')['original_title'].count().sort_values(ascending=False)
actor_high_budget

cast
Matt Damon           18
Adam Sandler         17
Angelina Jolie       16
Eddie Murphy         15
Samuel L. Jackson    15
                     ..
Leslie Bibb           1
Leonard Nimoy         1
Lennie James          1
Lena Olin             1
50 Cent               1
Name: original_title, Length: 1505, dtype: int64

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [141]:
answers['17'] = 'Action'

actor_nicolas_cage=data[data.cast.str.contains('Nicolas Cage')].copy()
actor_nicolas_cage.genres = actor_nicolas_cage.genres.str.split('|')
actor_nicolas_cage.explode('genres').groupby('genres').count().sort_values('genres',ascending=False)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,production_companies,release_date,vote_average,release_year,profit,Date,genresList
genres,,,,,,,,,,,,,,,,
War,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Thriller,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
Science Fiction,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Romance,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Mystery,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Horror,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
History,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Fantasy,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Family,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Drama,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Crime,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Comedy,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Animation,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Adventure,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Action,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17

# 18. Самый убыточный фильм от Paramount Pictures

In [142]:
answers['18'] = 'K-19: The Widowmaker (tt0267626)'

paramount_pictures=data[data.production_companies.str.contains('Paramount Pictures')].copy()
paramount_pictures[paramount_pictures.profit==paramount_pictures.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,Date,genresList
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures|Intermedia Films|National G...,7/19/2002,6.0,2002,-64831034,2002-07-19,"[Thriller, Drama, History]"

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [143]:
answers['19'] = 2015

best_year=data.copy()
best_year.groupby('release_year')['revenue'].sum().sort_values(ascending=False)

release_year
2015    25449202382
2014    23405862953
2013    23213799791
2012    23079001687
2011    22676791872
2010    21071204961
2009    20261791024
2008    18252781990
2007    18162406801
2004    15663430720
2005    15309425558
2006    14775042320
2003    14346123312
2002    14136361487
2001    13017764865
2000    10664099805
Name: revenue, dtype: int64

# 20. Какой самый прибыльный год для студии Warner Bros?

In [144]:
answers['20'] = 2014    

WB=data[data.production_companies.str.contains('Warner Bros.')].copy()
WB.groupby('release_year')['profit'].sum().sort_values(ascending=False)

release_year
2014    2295464519
2007    2201675217
2008    2134595031
2010    1974712985
2011    1871393682
2003    1855493377
2009    1822454136
2013    1636453400
2004    1631933725
2005    1551980298
2001    1343545668
2012    1258020056
2002    1022709901
2015     870368348
2006     620170743
2000     452631386
Name: profit, dtype: int64

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [145]:
answers['21'] = '9 - Сентябрь'

import datetime
movie_month.groupby(movie_month.release_date).count().sort_values('imdb_id',ascending=False)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,vote_average,release_year,profit
release_date,,,,,,,,,,,,,,
9,227,227,227,227,227,227,227,227,227,227,227,227,227,227
12,190,190,190,190,190,190,190,190,190,190,190,190,190,190
10,186,186,186,186,186,186,186,186,186,186,186,186,186,186
8,161,161,161,161,161,161,161,161,161,161,161,161,161,161
3,156,156,156,156,156,156,156,156,156,156,156,156,156,156
4,149,149,149,149,149,149,149,149,149,149,149,149,149,149
6,147,147,147,147,147,147,147,147,147,147,147,147,147,147
11,146,146,146,146,146,146,146,146,146,146,146,146,146,146
7,142,142,142,142,142,142,142,142,142,142,142,142,142,142
5,140,140,140,140,140,140,140,140,140,140,140,140,140,140
2,135,135,135,135,135,135,135,135,135,135,135,135,135,135
1,110,110,110,110,110,110,110,110,110,110,110,110,110,110

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [146]:
answers['22'] = 450

movie_month_summer=movie_month[movie_month.release_date.isin([6,7,8])].copy()
movie_month_summer.groupby(movie_month_summer.release_date).count().sum()[0]

450

# 23. Для какого режиссера зима – самое продуктивное время года?

In [147]:
answers['23'] = 'Peter Jackson'

movie_month_winter=movie_month[movie_month.release_date.isin([12,1,2])].copy()
movie_month_winter.director = movie_month_winter.director.str.split('|')
movie_month_winter = movie_month_winter.explode('director').groupby('director')['imdb_id'].count().sort_values(ascending=False)
movie_month_winter

director
Peter Jackson            7
Steven Soderbergh        6
Clint Eastwood           6
Martin Scorsese          4
Adam Shankman            4
                        ..
Matt Bettinelli-Olpin    1
Matt Reeves              1
Matthew O'Callaghan      1
Matthew Vaughn           1
Jon Avnet                1
Name: imdb_id, Length: 358, dtype: int64

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [148]:
answers['24'] = 'Four By Two Productions'

long_movie_names=data.copy()
long_movie_names['title_length']=long_movie_names['original_title'].map(lambda x: len(x))
companies = long_movie_names.production_companies.str.split('|').explode().unique()
sum_gen = pd.Series(dtype='float64', index=companies)
for comp in companies:
    sum_gen[comp] = long_movie_names['title_length'][long_movie_names['production_companies'].map(lambda x: True if comp in x else False)].mean()
sum_gen.sort_values(ascending=False).head()

Four By Two Productions      83.0
Jim Henson Company, The      59.0
Dos Corazones                47.0
Museum Canada Productions    46.0
Polsky Films                 46.0
dtype: float64

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [149]:
answers['25'] = 'Midnight Picture Show'

long_movie_names=data.copy()
long_movie_names['title_length']=long_movie_names['overview'].map(lambda x: len(x))
movies = long_movie_names.production_companies.str.split('|').explode().unique()
sum_gen = pd.Series(dtype='float64', index=movies)
for movie in movies:
    sum_gen[movie] = long_movie_names['title_length'][long_movie_names['production_companies'].map(lambda x: True if movie in x else False)].mean()
sum_gen.sort_values(ascending=False).head()

Midnight Picture Show               1000.0
Room 9 Entertainment                 964.0
Brookwell-McNamara Entertainment     936.0
Lions Gate Family Entertainment      909.0
Crest Animation Productions          909.0
dtype: float64

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

In [150]:
answers['26'] = 'Inside Out, The Dark Knight, 12 Years a Slave'

movies=data.copy()
movie_border = np.quantile(movies.vote_average, 0.99)
movies[movies.vote_average >= movie_border].sort_values(by='vote_average', ascending=False)['original_title']

599                                       The Dark Knight
9                                              Inside Out
34                                                   Room
118                                          Interstellar
125                                    The Imitation Game
370                                             Inception
1191                                     12 Years a Slave
1183                              The Wolf of Wall Street
1081        The Lord of the Rings: The Return of the King
872                                           The Pianist
1800                                              Memento
119                               Guardians of the Galaxy
138                              The Grand Budapest Hotel
128                                             Gone Girl
283                                            Mr. Nobody
1688                                  There Will Be Blood
1563                Eternal Sunshine of the Spotless Mind
1444                                         The Prestige
1213                                   Dallas Buyers Club
1205                                            Prisoners
124                                            Big Hero 6
1188                                                  Her
316                                              3 Idiots
863                 The Lord of the Rings: The Two Towers
155                              The Theory of Everything
28                                              Spotlight
177                                The Fault in Our Stars
496     The Lord of the Rings: The Fellowship of the Ring
Name: original_title, dtype: object

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [151]:
answers['27'] = 'Daniel Radcliffe , Rupert Grint'

cast_counter=data.copy()
cast_counter['cast_split'] = cast_counter['cast'].str.split('|')
cast_counter['cast_group']=cast_counter.cast_split.apply(lambda x: list(combinations(x, 2))).tolist()
counter_list= chain(*cast_counter['cast_group'])
Counter(counter_list).most_common()

[(('Daniel Radcliffe', 'Rupert Grint'), 8),
 (('Daniel Radcliffe', 'Emma Watson'), 8),
 (('Rupert Grint', 'Emma Watson'), 7),
 (('Ben Stiller', 'Owen Wilson'), 6),
 (('Johnny Depp', 'Helena Bonham Carter'), 6),
 (('Adam Sandler', 'Kevin James'), 5),
 (('Hugh Jackman', 'Ian McKellen'), 5),
 (('Kristen Stewart', 'Robert Pattinson'), 5),
 (('Kristen Stewart', 'Taylor Lautner'), 5),
 (('Robert Pattinson', 'Taylor Lautner'), 5),
 (('Jennifer Lawrence', 'Josh Hutcherson'), 4),
 (('Jennifer Lawrence', 'Liam Hemsworth'), 4),
 (('Jennifer Lawrence', 'Woody Harrelson'), 4),
 (('Josh Hutcherson', 'Liam Hemsworth'), 4),
 (('Josh Hutcherson', 'Woody Harrelson'), 4),
 (('Liam Hemsworth', 'Woody Harrelson'), 4),
 (('Tobin Bell', 'Costas Mandylor'), 4),
 (('Tobin Bell', 'Betsy Russell'), 4),
 (('Costas Mandylor', 'Betsy Russell'), 4),
 (('Vin Diesel', 'Jordana Brewster'), 4),
 (('Paul Walker', 'Jordana Brewster'), 4),
 (('Mike Myers', 'Eddie Murphy'), 4),
 (('Mike Myers', 'Cameron Diaz'), 4),
 (('Eddie Murphy', 'Cameron Diaz'), 4),
 (('Kristen Stewart', 'Peter Facinelli'), 4),
 (('Robert Pattinson', 'Peter Facinelli'), 4),
 (('Taylor Lautner', 'Peter Facinelli'), 4),
 (('George Clooney', 'Brad Pitt'), 4),
 (('Hugh Jackman', 'Halle Berry'), 4),
 (('Christian Bale', 'Michael Caine'), 4),
 (('Vin Diesel', 'Paul Walker'), 3),
 (('Vin Diesel', 'Michelle Rodriguez'), 3),
 (('Vin Diesel', 'Dwayne Johnson'), 3),
 (('Paul Walker', 'Michelle Rodriguez'), 3),
 (('Paul Walker', 'Dwayne Johnson'), 3),
 (('Robert Downey Jr.', 'Mark Ruffalo'), 3),
 (('Robert Downey Jr.', 'Scarlett Johansson'), 3),
 (('Chris Evans', 'Scarlett Johansson'), 3),
 (('Liam Neeson', 'Maggie Grace'), 3),
 (('Liam Neeson', 'Famke Janssen'), 3),
 (('Jennifer Lawrence', 'Elizabeth Banks'), 3),
 (('Josh Hutcherson', 'Elizabeth Banks'), 3),
 (('Liam Hemsworth', 'Elizabeth Banks'), 3),
 (('Woody Harrelson', 'Elizabeth Banks'), 3),
 (('Tom Cruise', 'Ving Rhames'), 3),
 (('Mark Wahlberg', 'Giovanni Ribisi'), 3),
 (('Johnny Depp', 'Paul Bettany'), 3),
 (('Adam Sandler', 'Steve Buscemi'), 3),
 (('Martin Freeman', 'Richard Armitage'), 3),
 (('Ian McKellen', 'Richard Armitage'), 3),
 (('Ben Stiller', 'Robin Williams'), 3),
 (('Patrick Stewart', 'Ian McKellen'), 3),
 (('Sylvester Stallone', 'Jason Statham'), 3),
 (('Sylvester Stallone', 'Arnold Schwarzenegger'), 3),
 (('Russell Crowe', 'Jennifer Connelly'), 3),
 (('Bradley Cooper', 'Ed Helms'), 3),
 (('Bradley Cooper', 'Zach Galifianakis'), 3),
 (('Bradley Cooper', 'Justin Bartha'), 3),
 (('Ed Helms', 'Zach Galifianakis'), 3),
 (('Ed Helms', 'Justin Bartha'), 3),
 (('Zach Galifianakis', 'Justin Bartha'), 3),
 (('Kristen Stewart', 'Ashley Greene'), 3),
 (('Robert Pattinson', 'Ashley Greene'), 3),
 (('Taylor Lautner', 'Ashley Greene'), 3),
 (('Bradley Cooper', 'Ken Jeong'), 3),
 (('David Cross', 'Justin Long'), 3),
 (('Jason Lee', 'Justin Long'), 3),
 (('Paul Rudd', 'Jason Segel'), 3),
 (('Shia LaBeouf', 'Josh Duhamel'), 3),
 (('Robert Downey Jr.', 'Gwyneth Paltrow'), 3),
 (('Daniel Radcliffe', 'Ralph Fiennes'), 3),
 (('Emma Watson', 'Ralph Fiennes'), 3),
 (('Rupert Grint', 'Ralph Fiennes'), 3),
 (('Skandar Keynes', 'Georgie Henley'), 3),
 (('Mike Myers', 'Antonio Banderas'), 3),
 (('Mike Myers', 'Julie Andrews'), 3),
 (('Eddie Murphy', 'Antonio Banderas'), 3),
 (('Eddie Murphy', 'Julie Andrews'), 3),
 (('Cameron Diaz', 'Antonio Banderas'), 3),
 (('Cameron Diaz', 'Julie Andrews'), 3),
 (('Steve Carell', 'Paul Rudd'), 3),
 (('Elijah Wood', 'Ian McKellen'), 3),
 (('Elijah Wood', 'Viggo Mortensen'), 3),
 (('Elijah Wood', 'Liv Tyler'), 3),
 (('Elijah Wood', 'Orlando Bloom'), 3),
 (('Ian McKellen', 'Viggo Mortensen'), 3),
 (('Ian McKellen', 'Liv Tyler'), 3),
 (('Ian McKellen', 'Orlando Bloom'), 3),
 (('Viggo Mortensen', 'Liv Tyler'), 3),
 (('Viggo Mortensen', 'Orlando Bloom'), 3),
 (('Liv Tyler', 'Orlando Bloom'), 3),
 (('George Clooney', 'Matt Damon'), 3),
 (('Brad Pitt', 'Julia Roberts'), 3),
 (('Jason Biggs', 'Thomas Ian Nicholas'), 3),
 (('Jason Biggs', 'Seann William Scott'), 3),
 (('Alexa PenaVega', 'Daryl Sabara'), 3),
 (('Antonio Banderas', 'Carla Gugino'), 3),
 (('Christian Bale', 'Gary Oldman'), 3),
 (('Michael Caine', 'Gary Oldman'), 3),
 (('Daniel Craig', 'Judi Dench'), 3),
 (('Jack Black', 'Angelina Jolie'), 3),
 (('Ben Stiller', 'David Schwimmer'), 3),
 (('Ben Stiller', 'Chris Rock'), 3),
 (('Ron Perlman', 'John Hurt'), 3),
 (('Hayden Christensen', 'Samuel L. Jackson'), 3),
 (('Jason Statham', 'FranÃ§ois BerlÃ©and'), 3),
 (('John Cho', 'Kal Penn'), 3),
 (('Johnny Depp', 'Geoffrey Rush'), 3),
 (('Johnny Depp', 'Bill Nighy'), 3),
 (('Ray Romano', 'Denis Leary'), 3),
 (('John Leguizamo', 'Denis Leary'), 3),
 (('Tobey Maguire', 'Kirsten Dunst'), 3),
 (('Tobey Maguire', 'James Franco'), 3),
 (('Kirsten Dunst', 'James Franco'), 3),
 (('Tim Allen', 'Spencer Breslin'), 3),
 (('Denzel Washington', 'Kimberly Elise'), 3),
 (('Ice Cube', 'Mike Epps'), 3),
 (('Johnny Depp', 'Orlando Bloom'), 3),
 (('Johnny Depp', 'Keira Knightley'), 3),
 (('Orlando Bloom', 'Keira Knightley'), 3),
 (('Patrick Stewart', 'Famke Janssen'), 3),
 (('Hugh Jackman', 'Famke Janssen'), 3),
 (('Ian McKellen', 'Famke Janssen'), 3),
 (('Halle Berry', 'Famke Janssen'), 3),
 (('Owen Wilson', 'Vince Vaughn'), 3),
 (('Bruce Willis', 'Kevin Pollak'), 3),
 (('Shailene Woodley', 'Theo James'), 2),
 (('Shailene Woodley', 'Kate Winslet'), 2),
 (('Shailene Woodley', 'Ansel Elgort'), 2),
 (('Shailene Woodley', 'Miles Teller'), 2),
 (('Theo James', 'Kate Winslet'), 2),
 (('Theo James', 'Miles Teller'), 2),
 (('Kate Winslet', 'Miles Teller'), 2),
 (('Leonardo DiCaprio', 'Tom Hardy'), 2),
 (('Daniel Craig', 'Ralph Fiennes'), 2),
 (('Robert Downey Jr.', 'Chris Hemsworth'), 2),
 (('Robert Downey Jr.', 'Chris Evans'), 2),
 (('Chris Hemsworth', 'Scarlett Johansson'), 2),
 (('Mark Ruffalo', 'Scarlett Johansson'), 2),
 (('Maggie Grace', 'Famke Janssen'), 2),
 (('Dwayne Johnson', 'Carla Gugino'), 2),
 (('Christian Bale', 'Melissa Leo'), 2),
 (('Steve Carell', 'Ryan Gosling'), 2),
 (('Tom Cruise', 'Jeremy Renner'), 2),
 (('Tom Cruise', 'Simon Pegg'), 2),
 (('Jeremy Renner', 'Simon Pegg'), 2),
 (('Mark Wahlberg', 'Seth MacFarlane'), 2),
 (('Seth MacFarlane', 'Giovanni Ribisi'), 2),
 (("Dylan O'Brien", 'Kaya Scodelario'), 2),
 (('Anna Kendrick', 'Rebel Wilson'), 2),
 (('Anna Kendrick', 'Brittany Snow'), 2),
 (('Anna Kendrick', 'Skylar Astin'), 2),
 (('Liam Neeson', 'Boyd Holbrook'), 2),
 (('Edgar RamÃ\xadrez', 'Delroy Lindo'), 2),
 (('Bradley Cooper', 'Sienna Miller'), 2),
 (('Miles Teller', 'Michael B. Jordan'), 2),
 (('Rose Byrne', 'Bobby Cannavale'), 2),
 (('Hugh Jackman', 'Amanda Seyfried'), 2),
 (('Joseph Gordon-Levitt', 'Seth Rogen'), 2),
 (('Seth Rogen', 'Lizzy Caplan'), 2),
 (('Adam Sandler', 'Andy Samberg'), 2),
 (('Adam Sandler', 'Selena Gomez'), 2),
 (('Will Ferrell', 'Mark Wahlberg'), 2),
 (('Kevin James', 'Raini Rodriguez'), 2),
 (('Tina Fey', 'Amy Poehler'), 2),
 (('Tom Kenny', 'Bill Fagerbakke'), 2),
 (('Tom Kenny', 'Rodger Bumpass'), 2),
 (('Tom Kenny', 'Clancy Brown'), 2),
 (('Tom Kenny', 'Carolyn Lawrence'), 2),
 (('Bill Fagerbakke', 'Carolyn Lawrence'), 2),
 (('Rodger Bumpass', 'Carolyn Lawrence'), 2),
 (('Clancy Brown', 'Carolyn Lawrence'), 2),
 (('Chris Evans', 'Sebastian Stan'), 2),
 (('Scarlett Johansson', 'Samuel L. Jackson'), 2),
 (('Martin Freeman', 'Ian McKellen'), 2),
 (('Martin Freeman', 'Ken Stott'), 2),
 (('Martin Freeman', 'Graham McTavish'), 2),
 (('Ian McKellen', 'Ken Stott'), 2),
 (('Ian McKellen', 'Graham McTavish'), 2),
 (('Richard Armitage', 'Ken Stott'), 2),
 (('Richard Armitage', 'Graham McTavish'), 2),
 (('Ken Stott', 'Graham McTavish'), 2),
 (('Hugh Jackman', 'Patrick Stewart'), 2),
 (('James McAvoy', 'Patrick Stewart'), 2),
 (('James McAvoy', 'Michael Fassbender'), 2),
 (('Megan Fox', 'Will Arnett'), 2),
 (('Mark Wahlberg', 'Stanley Tucci'), 2),
 (('Jason Bateman', 'Jason Sudeikis'), 2),
 (('Jason Bateman', 'Charlie Day'), 2),
 (('Jason Bateman', 'Jennifer Aniston'), 2),
 (('Andrew Garfield', 'Emma Stone'), 2),
 (('James Franco', 'Seth Rogen'), 2),
 (('James Franco', 'Lizzy Caplan'), 2),
 (('Jay Baruchel', 'Gerard Butler'), 2),
 (('Jay Baruchel', 'Jonah Hill'), 2),
 (('Gerard Butler', 'Jonah Hill'), 2),
 (('Jason Statham', 'Arnold Schwarzenegger'), 2),
 (('Meryl Streep', 'Emily Blunt'), 2),
 (('Lena Headey', 'David Wenham'), 2),
 (('Jonah Hill', 'Dave Franco'), 2),
 (('Channing Tatum', 'Dave Franco'), 2),
 (('Ben Whishaw', 'Michael Gambon'), 2),
 (('Russell Crowe', 'Logan Lerman'), 2),
 (('Zac Efron', 'Dave Franco'), 2),
 (('Ryan Guzman', 'Stephen Boss'), 2),
 (('Joaquin Phoenix', 'Reese Witherspoon'), 2),
 (('Jessica Alba', 'Josh Brolin'), 2),
 (('Jessica Alba', 'Rosario Dawson'), 2),
 (('Jesse Eisenberg', 'Anne Hathaway'), 2),
 (('Jesse Eisenberg', 'Leslie Mann'), 2),
 (('Anne Hathaway', 'Leslie Mann'), 2),
 (('George Clooney', 'Bill Murray'), 2),
 (('George Clooney', 'John Goodman'), 2),
 (('Kit Harington', 'Carrie-Anne Moss'), 2),
 (('Channing Tatum', 'Sienna Miller'), 2),
 (('Zac Efron', 'Imogen Poots'), 2),
 (('Michael Ealy', 'Regina Hall'), 2),
 (('Morgan Freeman', 'Ashley Judd'), 2),
 (('Morgan Freeman', 'Nathan Gamble'), 2),
 (('Morgan Freeman', 'Harry Connick Jr.'), 2),
 (('Ashley Judd', 'Nathan Gamble'), 2),
 (('Ashley Judd', 'Harry Connick Jr.'), 2),
 (('Michael Sheen', 'Shane Brolly'), 2),
 (('Chris Pine', 'Zachary Quinto'), 2),
 (('Robert Downey Jr.', 'Jude Law'), 2),
 (('John Cusack', 'Amanda Peet'), 2),
 (('Jennifer Connelly', 'Christopher Plummer'), 2),
 (('Jesse Eisenberg', 'Woody Harrelson'), 2),
 (('Kristen Stewart', 'Billy Burke'), 2),
 (('Robert Pattinson', 'Billy Burke'), 2),
 (('Bill Hader', 'Anna Faris'), 2),
 (('Bill Hader', 'James Caan'), 2),
 (('Anna Faris', 'James Caan'), 2),
 (('Susan Sarandon', 'Stanley Tucci'), 2),
 (('Jason Statham', 'Amy Smart'), 2),
 (('Jason Statham', 'Dwight Yoakam'), 2),
 (('Jason Statham', 'Efren Ramirez'), 2),
 (('Amy Smart', 'Dwight Yoakam'), 2),
 (('Amy Smart', 'Efren Ramirez'), 2),
 (('Vince Vaughn', 'Jon Favreau'), 2),
 (('Jason Bateman', 'Jon Favreau'), 2),
 (('Charlize Theron', 'Guy Pearce'), 2),
 (('Seth Rogen', 'Paul Rudd'), 2),
 (('Reese Witherspoon', 'Paul Rudd'), 2),
 (('Meryl Streep', 'Stanley Tucci'), 2),
 (('Johnny Depp', 'Giovanni Ribisi'), 2),
 (('Billy Crudup', 'Marion Cotillard'), 2),
 (('Matt Damon', 'Scott Bakula'), 2),
 (('Tobin Bell', 'Mark Rolston'), 2),
 (('Costas Mandylor', 'Mark Rolston'), 2),
 (('Betsy Russell', 'Mark Rolston'), 2),
 (('Shia LaBeouf', 'Megan Fox'), 2),
 (('Shia LaBeouf', 'Tyrese Gibson'), 2),
 (('Megan Fox', 'Tyrese Gibson'), 2),
 (('Josh Duhamel', 'Tyrese Gibson'), 2),
 (('Jeff Bridges', 'Kevin Spacey'), 2),
 (('Dwayne Johnson', 'Seann William Scott'), 2),
 (('Nicolas Cage', 'Eva Mendes'), 2),
 (('Seth Rogen', 'Leslie Mann'), 2),
 (('Naomi Watts', 'Armin Mueller-Stahl'), 2),
 (('Clive Owen', 'Paul Giamatti'), 2),
 (('Julia Roberts', 'Paul Giamatti'), 2),
 (('Jason Bateman', 'Kristen Wiig'), 2),
 (('Robert Downey Jr.', 'Jamie Foxx'), 2),
 (('Michael Caine', 'Emily Mortimer'), 2),
 (('Danny Huston', 'Lynn Collins'), 2),
 (('Robert Downey Jr.', 'Don Cheadle'), 2),
 (('Gwyneth Paltrow', 'Don Cheadle'), 2),
 (('Steve Carell', 'Russell Brand'), 2),
 (('Steve Carell', 'Will Arnett'), 2),
 (('Jason Segel', 'Russell Brand'), 2),
 (('Sylvester Stallone', 'Dolph Lundgren'), 2),
 (('Jason Statham', 'Dolph Lundgren'), 2),
 (('Russell Crowe', 'Mark Strong'), 2),
 (('Sam Worthington', 'Liam Neeson'), 2),
 (('Sam Worthington', 'Ralph Fiennes'), 2),
 (('Liam Neeson', 'Ralph Fiennes'), 2),
 (('Robert De Niro', 'Owen Wilson'), 2),
 (('Robert De Niro', 'Dustin Hoffman'), 2),
 (('Robert De Niro', 'Barbra Streisand'), 2),
 (('Ben Stiller', 'Dustin Hoffman'), 2),
 (('Ben Stiller', 'Barbra Streisand'), 2),
 (('Dustin Hoffman', 'Barbra Streisand'), 2),
 (('Logan Lerman', 'Brandon T. Jackson'), 2),
 (('Logan Lerman', 'Alexandra Daddario'), 2),
 (('Channing Tatum', 'Richard Jenkins'), 2),
 (('Danny Trejo', 'Michelle Rodriguez'), 2),
 (('Adam Sandler', 'Salma Hayek'), 2),
 (('Ashley Greene', 'Peter Facinelli'), 2),
 (('Brad Pitt', 'Jonah Hill'), 2),
 (('Mark Wahlberg', 'Dwayne Johnson'), 2),
 (('Helena Bonham Carter', 'Timothy Spall'), 2),
 (('Jake Gyllenhaal', 'Anne Hathaway'), 2),
 (('Tom Cruise', 'Cameron Diaz'), 2),
 (('Matt Damon', 'Greg Kinnear'), 2),
 (('Emily Blunt', 'Jason Segel'), 2),
 (('Jack Black', 'Amanda Peet'), 2),
 (('Christian Bale', 'Amy Adams'), 2),
 (('Katherine Heigl', 'Ashton Kutcher'), 2),
 (('Sarah Jessica Parker', 'Kristin Davis'), 2),
 (('Sarah Jessica Parker', 'Cynthia Nixon'), 2),
 (('Sarah Jessica Parker', 'Kim Cattrall'), 2),
 (('Sarah Jessica Parker', 'Chris Noth'), 2),
 (('Kristin Davis', 'Chris Noth'), 2),
 (('Cynthia Nixon', 'Chris Noth'), 2),
 (('Kim Cattrall', 'Chris Noth'), 2),
 (('Robert De Niro', 'Edward Norton'), 2),
 (('Zachary Gordon', 'Robert Capron'), 2),
 (('Zachary Gordon', 'Steve Zahn'), 2),
 (('Zachary Gordon', 'Rachael Harris'), 2),
 (('Robert Capron', 'Steve Zahn'), 2),
 (('Steve Zahn', 'Rachael Harris'), 2),
 (('Kristen Wiig', 'Maya Rudolph'), 2),
 (('Tyler Perry', 'Janet Jackson'), 2),
 (('Tyler Perry', 'Jill Scott'), 2),
 (('Tyler Perry', 'Malik Yoba'), 2),
 (('Janet Jackson', 'Malik Yoba'), 2),
 (('Jill Scott', 'Malik Yoba'), 2),
 (('Milla Jovovich', 'Ali Larter'), 2),
 (('John Goodman', 'Steve Buscemi'), 2),
 (('Billy Crystal', 'Steve Buscemi'), 2),
 (('RenÃ©e Zellweger', 'Colin Firth'), 2),
 (('RenÃ©e Zellweger', 'Hugh Grant'), 2),
 (('RenÃ©e Zellweger', 'Gemma Jones'), 2),
 (('RenÃ©e Zellweger', 'Jim Broadbent'), 2),
 (('Colin Firth', 'Gemma Jones'), 2),
 (('Colin Firth', 'Jim Broadbent'), 2),
 (('Hugh Grant', 'Gemma Jones'), 2),
 (('Hugh Grant', 'Jim Broadbent'), 2),
 (('George Clooney', 'Andy GarcÃ\xada'), 2),
 (('George Clooney', 'Julia Roberts'), 2),
 (('Brad Pitt', 'Matt Damon'), 2),
 (('Brad Pitt', 'Andy GarcÃ\xada'), 2),
 (('Brendan Fraser', 'John Hannah'), 2),
 (('Angelina Jolie', 'Noah Taylor'), 2),
 (('Russell Crowe', 'Paul Bettany'), 2),
 (('Jason Biggs', 'Chris Klein'), 2),
 (('Jason Biggs', 'Eddie Kaye Thomas'), 2),
 (('Seann William Scott', 'Eddie Kaye Thomas'), 2),
 (('Anne Hathaway', 'Julie Andrews'), 2),
 (('Anne Hathaway', 'Heather Matarazzo'), 2),
 (('Anne Hathaway', 'HÃ©ctor Elizondo'), 2),
 (('Julie Andrews', 'Heather Matarazzo'), 2),
 (('Julie Andrews', 'HÃ©ctor Elizondo'), 2),
 (('Ewan McGregor', 'Jim Broadbent'), 2),
 (('Johnny Depp', 'PenÃ©lope Cruz'), 2),
 (('Jude Law', 'Rachel Weisz'), 2),
 (('Heath Ledger', 'Shannyn Sossamon'), 2),
 (('Marlon Wayans', 'Shawn Wayans'), 2),
 (('Chris Tucker', 'Jackie Chan'), 2),
 (('Seth Green', 'Breckin Meyer'), 2),
 (('Breckin Meyer', 'Amy Smart'), 2),
 (('Brad Pitt', 'James Gandolfini'), 2),
 (('Anthony Hopkins', 'Hope Davis'), 2),
 (('Robert De Niro', 'Charlize Theron'), 2),
 (('DMX', 'Anthony Anderson'), 2),
 (('Mike Epps', 'Anna Maria Horsford'), 2),
 (('Jason Biggs', 'Amanda Detmer'), 2),
 (('Paul Walker', 'Vin Diesel'), 2),
 (('John Travolta', 'Vince Vaughn'), 2),
 (('Freddie Prinze Jr.', 'Matthew Lillard'), 2),
 (('Cary Elwes', 'Joanna Lumley'), 2),
 (('Jack Black', 'Dustin Hoffman'), 2),
 (('Jack Black', 'Jackie Chan'), 2),
 (('Dustin Hoffman', 'Jackie Chan'), 2),
 (('Angelina Jolie', 'Jackie Chan'), 2),
 (('Colin Firth', 'Stellan SkarsgÃ¥rd'), 2),
 (('Ben Stiller', 'Jada Pinkett Smith'), 2),
 (('David Schwimmer', 'Chris Rock'), 2),
 (('Ron Perlman', 'Selma Blair'), 2),
 (('Ron Perlman', 'Jeffrey Tambor'), 2),
 (('Selma Blair', 'Jeffrey Tambor'), 2),
 (('Selma Blair', 'John Hurt'), 2),
 (('William Moseley', 'Anna Popplewell'), 2),
 (('William Moseley', 'Skandar Keynes'), 2),
 (('William Moseley', 'Georgie Henley'), 2),
 (('Anna Popplewell', 'Skandar Keynes'), 2),
 (('Anna Popplewell', 'Georgie Henley'), 2),
 (('Hugh Jackman', 'David Wenham'), 2),
 (('George Clooney', 'Tilda Swinton'), 2),
 (('George Clooney', 'Richard Jenkins'), 2),
 (('Will Ferrell', 'John C. Reilly'), 2),
 (('Will Ferrell', 'Mary Steenburgen'), 2),
 (('Seth Rogen', 'Danny McBride'), 2),
 (('James Franco', 'Danny McBride'), 2),
 (('Mark Wahlberg', 'Mila Kunis'), 2),
 (('Paul Rudd', 'Elizabeth Banks'), 2),
 (('Angelina Jolie', 'John Malkovich'), 2),
 (('John Cho', 'Neil Patrick Harris'), 2),
 (('Kal Penn', 'Neil Patrick Harris'), 2),
 (('Tobin Bell', 'Scott Patterson'), 2),
 (('Scott Patterson', 'Betsy Russell'), 2),
 (('Javier Bardem', 'PenÃ©lope Cruz'), 2),
 (('Steve Carell', 'Seth Rogen'), 2),
 (('Robert De Niro', 'Carla Gugino'), 2),
 (('Adam Sandler', 'John Turturro'), 2),
 (('Sean Penn', 'Josh Brolin'), 2),
 (('Cheryl Hines', 'Jeff Daniels'), 2),
 (('Bruce Willis', 'Robin Wright'), 2),
 (('Chris Hemsworth', 'Natalie Portman'), 2),
 (('Chris Hemsworth', 'Tom Hiddleston'), 2),
 (('Chris Hemsworth', 'Anthony Hopkins'), 2),
 (('Natalie Portman', 'Tom Hiddleston'), 2),
 (('Natalie Portman', 'Anthony Hopkins'), 2),
 (('Tom Hiddleston', 'Anthony Hopkins'), 2),
 (('Ryan Gosling', 'Emma Stone'), 2),
 (('Ryan Gosling', 'Marisa Tomei'), 2),
 (('Bradley Cooper', 'Robert De Niro'), 2),
 (('Ed Helms', 'Ken Jeong'), 2),
 (('Zach Galifianakis', 'Ken Jeong'), 2),
 (('Justin Bartha', 'Ken Jeong'), 2),
 (('Asa Butterfield', 'Ben Kingsley'), 2),
 (('Matthew McConaughey', 'William H. Macy'), 2),
 (('Jim Cummings', 'Bud Luckey'), 2),
 (('Jim Cummings', 'Craig Ferguson'), 2),
 (('Tom Hanks', 'Julia Roberts'), 2),
 (('Antonio Banderas', 'Salma Hayek'), 2),
 (('Kate Winslet', 'Jude Law'), 2),
 (('Robert De Niro', 'Katherine Heigl'), 2),
 (('Robin Williams', 'Johnny A. Sanchez'), 2),
 (('David Arquette', 'Neve Campbell'), 2),
 (('David Arquette', 'Courteney Cox'), 2),
 (('Neve Campbell', 'Courteney Cox'), 2),
 (('Devon Bostick', 'Rachael Harris'), 2),
 (('Devon Bostick', 'Steve Zahn'), 2),
 (('Jason Lee', 'David Cross'), 2),
 (('Neil Patrick Harris', 'Hank Azaria'), 2),
 (('Cate Blanchett', 'Tom Hollander'), 2),
 (('James McAvoy', 'Maggie Smith'), 2),
 (('James McAvoy', 'Julie Walters'), 2),
 (('Philip Seymour Hoffman', 'Marisa Tomei'), 2),
 (('Katie Featherston', 'Sprague Grayden'), 2),
 (('Viggo Mortensen', 'Vincent Cassel'), 2),
 (('Paul Walker', 'Tyrese Gibson'), 2),
 (('Dwayne Johnson', 'Jordana Brewster'), 2),
 (('Ray Romano', 'John Leguizamo'), 2),
 (('Matt Damon', 'Franka Potente'), 2),
 (('Matt Damon', 'Chris Cooper'), 2),
 (('Matt Damon', 'Brian Cox'), 2),
 (('Franka Potente', 'Brian Cox'), 2),
 (('Milla Jovovich', 'Michelle Rodriguez'), 2),
 (('Ewan McGregor', 'Natalie Portman'), 2),
 (('Ewan McGregor', 'Hayden Christensen'), 2),
 (('Ewan McGregor', 'Ian McDiarmid'), 2),
 (('Ewan McGregor', 'Samuel L. Jackson'), 2),
 (('Natalie Portman', 'Hayden Christensen'), 2),
 (('Natalie Portman', 'Ian McDiarmid'), 2),
 (('Natalie Portman', 'Samuel L. Jackson'), 2),
 (('Hayden Christensen', 'Ian McDiarmid'), 2),
 (('Ian McDiarmid', 'Samuel L. Jackson'), 2),
 (('Leonardo DiCaprio', 'Martin Sheen'), 2),
 (('Tom Hanks', 'Amy Adams'), 2),
 (('Adrien Brody', 'Thomas Kretschmann'), 2),
 (('Jennifer Lopez', 'Stanley Tucci'), 2),
 (('Wesley Snipes', 'Kris Kristofferson'), 2),
 (('Johnny Knoxville', 'Bam Margera'), 2),
 (('Johnny Knoxville', 'Steve-O'), 2),
 (('Johnny Knoxville', 'Chris Pontius'), 2),
 (('Bam Margera', 'Steve-O'), 2),
 (('Bam Margera', 'Chris Pontius'), 2),
 (('Steve-O', 'Chris Pontius'), 2),
 (('Meryl Streep', 'Chris Cooper'), 2),
 (('Ice Cube', 'Cedric the Entertainer'), 2),
 (('Ice Cube', 'Sean Patrick Thomas'), 2),
 (('Cedric the Entertainer', 'Sean Patrick Thomas'), 2),
 (('Antonio Banderas', 'Alexa PenaVega'), 2),
 (('Antonio Banderas', 'Daryl Sabara'), 2),
 (('Carla Gugino', 'Alexa PenaVega'), 2),
 (('Carla Gugino', 'Daryl Sabara'), 2),
 (('Ice Cube', 'John Witherspoon'), 2),
 (('Ice Cube', 'Don Curry'), 2),
 (('Mike Epps', 'John Witherspoon'), 2),
 (('Mike Epps', 'Don Curry'), 2),
 (('John Witherspoon', 'Don Curry'), 2),
 (('Bruce Willis', 'Cole Hauser'), 2),
 (('Chris Rock', 'Kerry Washington'), 2),
 (('Jamie Foxx', 'Kerry Washington'), 2),

ВАРИАНТ 2

# Submission

In [152]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': 'Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': 'Gods and Generals (tt0279111)',
 '3': 'Winnie the Pooh (tt1449283)',
 '4': 109.6585494970884,
 '5': 107.0,
 '6': 'Avatar (tt0499549)',
 '7': 'The Lone Ranger (tt1210819)',
 '8': 1478,
 '9': 'The Dark Knight (tt0468569)',
 '10': 'The Lone Ranger (tt1210819)',
 '11': 'Drama',
 '12': 'Action',
 '13': 'Peter Jackson',
 '14': 'Robert Rodriguez',
 '15': 'Chris Hemsworth',
 '16': 'Matt Damon',
 '17': 'Action',
 '18': 'K-19: The Widowmaker (tt0267626)',
 '19': 2015,
 '20': 2014,
 '21': '9 - Сентябрь',
 '22': 450,
 '23': 'Peter Jackson',
 '24': 'Four By Two Productions',
 '25': 'Midnight Picture Show',
 '26': 'Inside Out, The Dark Knight, 12 Years a Slave',
 '27': 'Daniel Radcliffe , Rupert Grint'}

In [153]:
# и убедиться что ни чего не пропустил)
len(answers)

27